apiVersion: v1
kind: Service
metadata:
  name: examen-app
  labels:
    app: examen-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 3200
  selector:
    app: examen-app